{{- range .Values.uuids }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ . }}
spec:
  schedule: "* * * * *"
  suspend: true 
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: "keystone"
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - "keystone" # Ensure this label uniquely identifies your job pods
                topologyKey: "kubernetes.io/hostname"
          containers:
          - name: worker
            image: iad.ocir.io/ax5gr8jsnjx1/keystone:latest
            imagePullPolicy: Always
            command: 
              - /bin/bash
              - -c
            args: 
              - python 
              - src/main.py 
              - -f 
              - files 
              - --filename 
              - "{{ . }}" 
              - -d
              - "true"
            resources:
              requests:
                cpu: 14000m
                memory: 23Gi
              limits:
                cpu: 15000m
                memory: 25Gi
            env:
              - name: FILE_ID
                value: "{{ . }}"
              - name: FILE_PATH
                value: "files"
          restartPolicy: OnFailure
      backoffLimit: 10
      ttlSecondsAfterFinished: 0
---
{{- end }}
