{{- range .Values.uuids }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-job-{{ . }}
spec:
  template:
    spec:
      containers:
      - name: worker
        image: iad.ocir.io/ax5gr8jsnjx1/keystone:latest
        command: 
          - python
          - src/main.py 
          - -f 
          - "files" 
          - --filename 
          - {{ . }}
          - -d
          - "True"
      restartPolicy: OnFailure
  backoffPolicy:
    type: BackoffPeriodic
    periodSeconds: 30
    maxAttempts: 3
---
{{- end }}
