{{- range .Values.uuids }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-job-{{ . }}
spec:
  template:
    spec:
      priorityClassName: non-preempting-priority-class
      containers:
      - name: worker
        image: iad.ocir.io/ax5gr8jsnjx1/keystone:latest
        imagePullPolicy: Always
        command: 
          - /bin/bash
          - -c
        args: ["./run.sh"]
        resources:
          requests:
            cpu: 7000m
            memory: 20Gi
          limits:
            cpu: 7200m
            memory: 25Gi
        env:
          - name: FILE_ID
            value: "{{ . }}"
          - name: FILE_PATH
            value: "files"
      restartPolicy: OnFailure
  backoffLimit: 10
  ttlSecondsAfterFinished: 0
---
{{- end }}
